✅ 1. Setup and Environment Checks

In [1]:
import torch
print("Imported PyTorch")

print("PyTorch version:", torch.__version__)

print("Is CUDA GPU available?:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Device Name:", torch.cuda.get_device_name())
else:
    print("No GPU available. Using CPU.")

# Type check example
a = torch.tensor([1, 2, 3])
print("Type of variable a:", type(a))

Imported PyTorch
PyTorch version: 2.9.0+cpu
Is CUDA GPU available?: False
No GPU available. Using CPU.
Type of variable a: <class 'torch.Tensor'>


✅ 2. Tensor Creation Methods

In [2]:
print("torch.empty((2,3)) creates uninitialized tensor:")
print(torch.empty((2, 3)))

print("\ntorch.zeros((2,3)) creates all-zeros tensor:")
print(torch.zeros((2, 3)))

print("\ntorch.ones((2,3)) creates all-ones tensor:")
print(torch.ones((2, 3)))

print("\ntorch.rand((2,3)) creates random values between 0 and 1:")
print(torch.rand((2, 3)))

print("\nSetting manual seed for reproducibility (seed=100):")
torch.manual_seed(100)
print(torch.rand((2, 3)))

print("\nCustom tensor from list:")
print(torch.tensor([10, 20, 30]))

print("\ntorch.arange creates evenly spaced values:")
print(torch.arange(0, 10, 2))

print("\ntorch.linspace creates fixed number of points:")
print(torch.linspace(0, 10, 10))

print("\nIdentity matrix using torch.eye:")
print(torch.eye(5))

print("\ntorch.full creates tensor filled with a value:")
print(torch.full((3, 3), 5))


torch.empty((2,3)) creates uninitialized tensor:
tensor([[2.6678e-23, 8.9823e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

torch.zeros((2,3)) creates all-zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

torch.ones((2,3)) creates all-ones tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

torch.rand((2,3)) creates random values between 0 and 1:
tensor([[0.7751, 0.8638, 0.3803],
        [0.3914, 0.7150, 0.8430]])

Setting manual seed for reproducibility (seed=100):
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

Custom tensor from list:
tensor([10, 20, 30])

torch.arange creates evenly spaced values:
tensor([0, 2, 4, 6, 8])

torch.linspace creates fixed number of points:
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

Identity matrix using torch.eye:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
     

✅ 3. Tensor Information, Shape, and Data Types

In [3]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)

print("Tensor x:\n", x)
print("\nShape of x:", x.shape)
print("Data type of x:", x.dtype)

print("\nCreate tensor with specific dtype torch.float64:")
y = torch.tensor([1.5, 2.5], dtype=torch.float64)
print(y)

print("\nChange dtype of x to float32:")
x_float = x.to(torch.float32)
print(x_float)

print("\nempty_like(x):")
print(torch.empty_like(x))

print("\nzeros_like(x):")
print(torch.zeros_like(x))

print("\nones_like(x):")
print(torch.ones_like(x))

print("\nrand_like(x) but force float values using dtype:")
print(torch.rand_like(x, dtype=torch.float32))


Tensor x:
 tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

Shape of x: torch.Size([2, 3])
Data type of x: torch.int32

Create tensor with specific dtype torch.float64:
tensor([1.5000, 2.5000], dtype=torch.float64)

Change dtype of x to float32:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

empty_like(x):
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

zeros_like(x):
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

ones_like(x):
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

rand_like(x) but force float values using dtype:
tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])


✅ 4. Mathematical Operations

In [4]:
#A. Scalar Operations
x = torch.tensor([1, 2, 3], dtype=torch.float32)

print("x + 2:", x + 2)
print("x - 2:", x - 2)
print("x * 2:", x * 2)
print("x / 2:", x / 2)

print("\nInteger division (x * 100 // 3):", x * 100 // 3)

print("\nModulus (x % 2):", x % 2)

print("\nPower (x ** 2):", x ** 2)


x + 2: tensor([3., 4., 5.])
x - 2: tensor([-1.,  0.,  1.])
x * 2: tensor([2., 4., 6.])
x / 2: tensor([0.5000, 1.0000, 1.5000])

Integer division (x * 100 // 3): tensor([ 33.,  66., 100.])

Modulus (x % 2): tensor([1., 0., 1.])

Power (x ** 2): tensor([1., 4., 9.])


In [5]:
# B. Element-wise Tensor Operations
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)

c = torch.tensor([-3.5, 2.2, -1.1])
print("\nAbsolute:", torch.absolute(c))
print("Negative:", c.neg())

d = torch.tensor([2.1, 2.9, 3.7])
print("\nRound:", torch.round(d))
print("Ceil:", d.ceil())
print("Floor:", d.floor())

print("\nClamp d between 2 and 3:", torch.clamp(d, 2, 3))


a + b: tensor([5, 7, 9])
a - b: tensor([-3, -3, -3])
a * b: tensor([ 4, 10, 18])
a / b: tensor([0.2500, 0.4000, 0.5000])

Absolute: tensor([3.5000, 2.2000, 1.1000])
Negative: tensor([ 3.5000, -2.2000,  1.1000])

Round: tensor([2., 3., 4.])
Ceil: tensor([3., 3., 4.])
Floor: tensor([2., 2., 3.])

Clamp d between 2 and 3: tensor([2.1000, 2.9000, 3.0000])


In [6]:
#C. Reduction Operations
e = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

print("Sum (all values):", torch.sum(e))
print("Sum by column:", torch.sum(e, dim=0))

print("\nMean (overall):", torch.mean(e))
print("Mean by column:", torch.mean(e, dim=0))

print("\nMedian:", torch.median(e))
print("Max:", torch.max(e))
print("Min:", torch.min(e))

items = torch.tensor([2, 3, 4])
print("\nProduct:", torch.prod(items))

stats = torch.tensor([2., 4., 4., 5., 5., 7., 9.])
print("\nStd Dev:", torch.std(stats))
print("Variance:", torch.var(stats))

print("\nArgmax (index of max):", torch.argmax(e))
print("Argmin (index of min):", torch.argmin(e))


Sum (all values): tensor(21.)
Sum by column: tensor([5., 7., 9.])

Mean (overall): tensor(3.5000)
Mean by column: tensor([2.5000, 3.5000, 4.5000])

Median: tensor(3.)
Max: tensor(6.)
Min: tensor(1.)

Product: tensor(24)

Std Dev: tensor(2.2678)
Variance: tensor(5.1429)

Argmax (index of max): tensor(5)
Argmin (index of min): tensor(0)


In [7]:
#D. Matrix and Linear Algebra Operations
f = torch.tensor([[1., 2.], [3., 4.]])
g = torch.tensor([[5., 6.], [7., 8.]])

print("Matrix multiplication:", torch.matmul(f, g))

v1 = torch.tensor([1., 2., 3.])
v2 = torch.tensor([4., 5., 6.])
print("\nDot product:", torch.dot(v1, v2))

print("\nTranspose of f:\n", torch.transpose(f, 0, 1))

print("\nDeterminant of f:", torch.det(f))

print("\nInverse of f:\n", torch.inverse(f))


Matrix multiplication: tensor([[19., 22.],
        [43., 50.]])

Dot product: tensor(32.)

Transpose of f:
 tensor([[1., 3.],
        [2., 4.]])

Determinant of f: tensor(-2.)

Inverse of f:
 tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [8]:
#E. Comparison + Special Functions
i = torch.tensor([1, 3, 5])
j = torch.tensor([2, 3, 4])

print("i > j:", i > j)
print("i < j:", i < j)
print("i == j:", i == j)

k = torch.tensor([1.0, 2.0, 3.0])

print("\nLog:", torch.log(k))
print("Exp:", torch.exp(k))
print("Sqrt:", torch.sqrt(k))
print("Sigmoid:", torch.sigmoid(k))
print("Softmax dim=0:", torch.softmax(k, dim=0))
print("ReLU:", torch.relu(k))


i > j: tensor([False, False,  True])
i < j: tensor([ True, False, False])
i == j: tensor([False,  True, False])

Log: tensor([0.0000, 0.6931, 1.0986])
Exp: tensor([ 2.7183,  7.3891, 20.0855])
Sqrt: tensor([1.0000, 1.4142, 1.7321])
Sigmoid: tensor([0.7311, 0.8808, 0.9526])
Softmax dim=0: tensor([0.0900, 0.2447, 0.6652])
ReLU: tensor([1., 2., 3.])


In [9]:
#✅ 5. Advanced Tensor Manipulation
m = torch.tensor([1., -2., 3.])
n = torch.tensor([10., 20., 30.])

print("Before in-place add:", m)
m.add_(n)
print("After in-place add:", m)

print("\nBefore ReLU:", m)
m.relu_()
print("After in-place ReLU:", m)

# Copying
a = torch.tensor([1, 2, 3])
b = a
print("\nAssignment b = a shares memory. id(a)==id(b) →", id(a) == id(b))

c = a.clone()
print("Clone creates a true copy. id(a)==id(c) →", id(a) == id(c))

# Reshaping
x = torch.arange(16)
print("\nReshape to (2,2,4):\n", x.reshape(2, 2, 4))

print("\nFlatten x:", x.flatten())

y = torch.randn(2, 3, 4)
print("\nOriginal shape:", y.shape)
print("Permuted shape (2,3,4 → 4,2,3):", y.permute(2, 0, 1).shape)

z = torch.tensor([1, 2, 3])
print("\nUnsqueeze at dim=0:", z.unsqueeze(0))
print("Squeeze (remove dim=0):", z.unsqueeze(0).squeeze(0))


Before in-place add: tensor([ 1., -2.,  3.])
After in-place add: tensor([11., 18., 33.])

Before ReLU: tensor([11., 18., 33.])
After in-place ReLU: tensor([11., 18., 33.])

Assignment b = a shares memory. id(a)==id(b) → True
Clone creates a true copy. id(a)==id(c) → False

Reshape to (2,2,4):
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]])

Flatten x: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Original shape: torch.Size([2, 3, 4])
Permuted shape (2,3,4 → 4,2,3): torch.Size([4, 2, 3])

Unsqueeze at dim=0: tensor([[1, 2, 3]])
Squeeze (remove dim=0): tensor([1, 2, 3])


In [10]:
# ✅ 7. NumPy Interoperability
import numpy as np
print("Imported NumPy")

np_arr = np.array([1, 2, 3])
torch_tensor = torch.from_numpy(np_arr)
print("\nNumPy → Torch:", torch_tensor)

back_to_numpy = torch_tensor.numpy()
print("Torch → NumPy:", back_to_numpy)


Imported NumPy

NumPy → Torch: tensor([1, 2, 3], dtype=torch.int32)
Torch → NumPy: [1 2 3]
