In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train


array([[-0.40213391, -0.38819252, -0.45526166, ..., -1.18993189,
        -1.17680271, -1.31066142],
       [ 3.20197173,  1.29914673,  3.32851967, ...,  2.6031412 ,
        -0.87944617,  1.14717878],
       [-0.09650575, -0.82634138, -0.14635596, ..., -1.23534342,
        -1.65570325, -0.88047088],
       ...,
       [-1.26077604, -0.05025855, -1.25156119, ..., -1.0420417 ,
         0.4367478 , -0.22340279],
       [ 0.14280686, -0.84964717,  0.0338042 , ..., -0.85676269,
        -0.60556514, -1.49150585],
       [ 0.98760922, -0.00364697,  0.97097143, ...,  1.19841144,
         0.01731857, -0.3012207 ]])

In [10]:
y_train

429    B
82     M
442    B
20     B
523    B
      ..
419    B
306    B
424    B
311    B
201    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,

### Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()


In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [20]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1, dtype= torch.float32, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float32, requires_grad=True)
    def forward(self, X):
        z= torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
    

In [17]:
## Important parameters
learning_rate= 0.1
epochs=25

In [21]:
#training
model = MySimpleNN(X_train_tensor)
model.weights
for epoch in range(epochs):

     #Forward pass
     y_pred = model.forward(X_train_tensor)
     #print(y_pred)


    #loss calculate
     loss = model.loss_function(y_pred, y_train_tensor)
     
     #backword pass
     loss.backward()


     #parameters update, 
     with torch.no_grad(): # For not tracking gradient here
        model.weights-=learning_rate * model.weights.grad
        model.bias-= learning_rate * model.bias.grad
        
    #zero gradient  # To not accumalate gradient
     model.weights.grad.zero_()
     model.bias.grad.zero_()
    #Print loss
     print(f"Epoch: {epoch+1}, loss: {loss.item()}")
     



Epoch: 1, loss: 3.4736900329589844
Epoch: 2, loss: 3.3375494480133057
Epoch: 3, loss: 3.197540044784546
Epoch: 4, loss: 3.0573010444641113
Epoch: 5, loss: 2.914172410964966
Epoch: 6, loss: 2.768662929534912
Epoch: 7, loss: 2.6198511123657227
Epoch: 8, loss: 2.4618523120880127
Epoch: 9, loss: 2.3020431995391846
Epoch: 10, loss: 2.143686532974243
Epoch: 11, loss: 1.9836167097091675
Epoch: 12, loss: 1.8270740509033203
Epoch: 13, loss: 1.6798564195632935
Epoch: 14, loss: 1.5429797172546387
Epoch: 15, loss: 1.4134129285812378
Epoch: 16, loss: 1.2975941896438599
Epoch: 17, loss: 1.1925783157348633
Epoch: 18, loss: 1.1031454801559448
Epoch: 19, loss: 1.0293382406234741
Epoch: 20, loss: 0.9701436758041382
Epoch: 21, loss: 0.9236375689506531
Epoch: 22, loss: 0.8874213695526123
Epoch: 23, loss: 0.8591229319572449
Epoch: 24, loss: 0.8366994261741638
Epoch: 25, loss: 0.8185704350471497


In [22]:
model.weights

tensor([[ 0.1968],
        [-0.0037],
        [ 0.0338],
        [ 0.1468],
        [ 0.0316],
        [ 0.1392],
        [ 0.1994],
        [-0.1735],
        [ 0.3281],
        [ 0.1609],
        [-0.2869],
        [ 0.3096],
        [-0.1175],
        [ 0.2129],
        [ 0.5626],
        [-0.2273],
        [ 0.0207],
        [-0.0133],
        [-0.0133],
        [ 0.3194],
        [-0.3724],
        [ 0.0298],
        [ 0.5104],
        [-0.0740],
        [ 0.1633],
        [-0.4393],
        [-0.0784],
        [-0.2264],
        [ 0.4472],
        [-0.2558]], requires_grad=True)

In [23]:
model.bias

tensor([-0.1463], requires_grad=True)

In [24]:
#Evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5184672474861145


In [28]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float32, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float32, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


### Important Parameters

In [26]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [29]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():  #To not track gradient here
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients , to  not accumate gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 4.012610912322998
Epoch: 2, Loss: 3.898456335067749
Epoch: 3, Loss: 3.778489828109741
Epoch: 4, Loss: 3.6573500633239746
Epoch: 5, Loss: 3.5286149978637695
Epoch: 6, Loss: 3.3946518898010254
Epoch: 7, Loss: 3.2562828063964844
Epoch: 8, Loss: 3.1127312183380127
Epoch: 9, Loss: 2.962118148803711
Epoch: 10, Loss: 2.809065818786621
Epoch: 11, Loss: 2.6479341983795166
Epoch: 12, Loss: 2.4864094257354736
Epoch: 13, Loss: 2.319244623184204
Epoch: 14, Loss: 2.153815984725952
Epoch: 15, Loss: 1.9901200532913208
Epoch: 16, Loss: 1.8302905559539795
Epoch: 17, Loss: 1.679955005645752
Epoch: 18, Loss: 1.5370005369186401
Epoch: 19, Loss: 1.4050240516662598
Epoch: 20, Loss: 1.283604383468628
Epoch: 21, Loss: 1.1779180765151978
Epoch: 22, Loss: 1.0883663892745972
Epoch: 23, Loss: 1.0149729251861572
Epoch: 24, Loss: 0.9570441246032715
Epoch: 25, Loss: 0.9129980802536011


In [30]:
model.bias

tensor([-0.1086], requires_grad=True)

### Evaluation

In [31]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6084949374198914


🚀 1. Improvements Planned (Notebook Cell with Print Explanation)

In [32]:
print("Training Pipeline Improvements Implemented:")
print("1️⃣ Model defined using nn.Linear instead of manual weights/bias.")
print("2️⃣ Activation functions from nn (Sigmoid, ReLU).")
print("3️⃣ Built-in loss function (nn.BCELoss).")
print("4️⃣ Parameter updates using torch.optim.SGD.")

Training Pipeline Improvements Implemented:
1️⃣ Model defined using nn.Linear instead of manual weights/bias.
2️⃣ Activation functions from nn (Sigmoid, ReLU).
3️⃣ Built-in loss function (nn.BCELoss).
4️⃣ Parameter updates using torch.optim.SGD.


### Simple  one  node network

In [33]:
#practice one neural  layer
# 5 features and 1 output , binary classification
import torch 
import torch.nn as nn
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid= nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out= self.sigmoid(out)
        return out 

In [34]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5988],
        [0.6017],
        [0.5174],
        [0.5045],
        [0.5135],
        [0.4542],
        [0.4963],
        [0.5032],
        [0.4679],
        [0.5583]], grad_fn=<SigmoidBackward0>)

In [35]:
model.linear

Linear(in_features=5, out_features=1, bias=True)

In [36]:
model.linear.weight

Parameter containing:
tensor([[-0.2896, -0.1395,  0.2355,  0.3179, -0.0629]], requires_grad=True)

In [37]:
model.linear.bias

Parameter containing:
tensor([0.0970], requires_grad=True)

In [38]:
from torchinfo import summary
summary(model, input_size= (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Simple 3 node in 1st layer and one  node  in second  layer network

In [39]:
#Practice with 3 neuron in first layer and one neuron in second layer
import torch
import torch.nn as nn
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features, 3) #Linear 1 is the name of the  first layer, with 5 input and 3 ouput
        self.relu = nn.ReLU()    #Applying ReLU on it 
        self.linear2 = nn.Linear(3,1)  # Linear 2 is the name of the second layer with 3 input and one output 
        self.sigmoid = nn.Sigmoid()    #Applying Sigmoid on it
    
    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out= self.linear2(out)
        out = self.sigmoid(out)
        
        return out


In [40]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.2929],
        [0.3292],
        [0.2956],
        [0.3517],
        [0.3208],
        [0.3538],
        [0.3335],
        [0.3030],
        [0.3124],
        [0.3027]], grad_fn=<SigmoidBackward0>)

In [41]:
model.linear1.weight

Parameter containing:
tensor([[-0.1598, -0.0681,  0.3176,  0.4295,  0.1287],
        [ 0.2043, -0.2830, -0.2448,  0.3690, -0.2016],
        [ 0.2320,  0.0190,  0.3477,  0.3712,  0.2646]], requires_grad=True)

In [42]:
model.linear1.bias

Parameter containing:
tensor([-0.2490,  0.4317, -0.4082], requires_grad=True)

In [43]:
from torchinfo import summary
summary(model, input_size= (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Same network Sequential container 

In [44]:
import torch 
import torch.nn as nn
class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out 

In [45]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4810],
        [0.5023],
        [0.4831],
        [0.4794],
        [0.4980],
        [0.4850],
        [0.4901],
        [0.4970],
        [0.4989],
        [0.4945]], grad_fn=<SigmoidBackward0>)

##### How to find the weights of the layer like we did before ?

In [46]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [47]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [48]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.network(features)
        return out 
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Binary cross entropy manually
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

In [49]:
learning_rate= 0.1
epochs= 25

In [50]:
model = MySimpleNN(X_train_tensor.shape[1])

for epoch in range(epochs):
    # Forward
    y_pred = model(X_train_tensor)
    #Losss
    loss= model.loss_function(y_pred, y_train_tensor)
    #Calculate gradient/ Backward pass
    loss.backward()
    #Update weight
    with torch.no_grad(): #So that it does not track gradient while updating weight
        for param in model.parameters():        # FIXED
            param -= learning_rate * param.grad

    #Gradient not to accumalate
     # Reset gradients
    model.zero_grad()  
    print(f"Epoch : {epoch+1}, loss: {loss.item()}")


Epoch : 1, loss: 0.7314310073852539
Epoch : 2, loss: 0.7263287901878357
Epoch : 3, loss: 0.7216006517410278
Epoch : 4, loss: 0.717167317867279
Epoch : 5, loss: 0.7130776643753052
Epoch : 6, loss: 0.7093329429626465
Epoch : 7, loss: 0.7058620452880859
Epoch : 8, loss: 0.7026875019073486
Epoch : 9, loss: 0.6997913718223572
Epoch : 10, loss: 0.6971470713615417
Epoch : 11, loss: 0.694744884967804
Epoch : 12, loss: 0.6925541162490845
Epoch : 13, loss: 0.6905393600463867
Epoch : 14, loss: 0.6887276768684387
Epoch : 15, loss: 0.687079906463623
Epoch : 16, loss: 0.6855831146240234
Epoch : 17, loss: 0.6842206716537476
Epoch : 18, loss: 0.682981014251709
Epoch : 19, loss: 0.6818594336509705
Epoch : 20, loss: 0.6808431148529053
Epoch : 21, loss: 0.6799180507659912
Epoch : 22, loss: 0.6790823936462402
Epoch : 23, loss: 0.6783280372619629
Epoch : 24, loss: 0.6776466965675354
Epoch : 25, loss: 0.6770285367965698


### Using built in loss function 

In [51]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.network(features)
        return out 
    
criterion = nn.BCELoss()

    

In [52]:
model = MySimpleNN(X_train_tensor.shape[1])
for epoch in range(epochs):
    # Forward
    y_pred= model(X_train_tensor)
    #Loss
    loss = criterion(y_pred, y_train_tensor.view(-1,1))

    #Backward pass
    loss.backward()

    #parameterss update
    with torch.no_grad():
        for param in model.parameters():
            param-=learning_rate*param.grad
   #Gradient not to accumalate
   # Reset gradients
    model.zero_grad()  
    print(f"Epoch : {epoch+1}, loss: {loss.item()}")
    

Epoch : 1, loss: 0.6865769624710083
Epoch : 2, loss: 0.674626350402832
Epoch : 3, loss: 0.6640343070030212
Epoch : 4, loss: 0.6531378626823425
Epoch : 5, loss: 0.6419836282730103
Epoch : 6, loss: 0.6297799944877625
Epoch : 7, loss: 0.6164185404777527
Epoch : 8, loss: 0.6016473174095154
Epoch : 9, loss: 0.5856695771217346
Epoch : 10, loss: 0.5687410831451416
Epoch : 11, loss: 0.5513021349906921
Epoch : 12, loss: 0.5331749320030212
Epoch : 13, loss: 0.5150456428527832
Epoch : 14, loss: 0.49712735414505005
Epoch : 15, loss: 0.4797016382217407
Epoch : 16, loss: 0.4628044664859772
Epoch : 17, loss: 0.4464823603630066
Epoch : 18, loss: 0.43085411190986633
Epoch : 19, loss: 0.41582393646240234
Epoch : 20, loss: 0.40143895149230957
Epoch : 21, loss: 0.3876883387565613
Epoch : 22, loss: 0.3744199573993683
Epoch : 23, loss: 0.36177858710289
Epoch : 24, loss: 0.34971508383750916
Epoch : 25, loss: 0.3382209837436676


In [53]:
model.parameters

<bound method Module.parameters of MySimpleNN(
  (network): Sequential(
    (0): Linear(in_features=30, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)>

In [54]:
#1. View first layer weights and bias
print(model.network[0].weight)
print(model.network[0].bias)

Parameter containing:
tensor([[-0.0076, -0.0615,  0.2904, -0.0164, -0.0414,  0.1766,  0.0421, -0.0319,
         -0.0023, -0.1339,  0.0679, -0.0460,  0.1606,  0.1207, -0.1481,  0.1810,
         -0.1164,  0.1347,  0.0971, -0.1842, -0.0337,  0.2493,  0.2297, -0.0319,
          0.1155,  0.2716,  0.1964,  0.1150,  0.0271,  0.2436],
        [-0.1144, -0.0306, -0.1699,  0.0457, -0.1047, -0.0928, -0.1242, -0.0845,
         -0.1649, -0.1445, -0.2141,  0.0947, -0.1425, -0.2213, -0.1451, -0.1707,
         -0.1861, -0.1212, -0.1022, -0.2056, -0.2244,  0.0426, -0.1564, -0.2629,
         -0.1092,  0.0028,  0.0344,  0.0326, -0.0769, -0.0557],
        [ 0.2400,  0.0191,  0.1018, -0.0475,  0.0629,  0.0875,  0.1501,  0.2464,
          0.1296, -0.1849,  0.1248, -0.0286,  0.0960, -0.0579,  0.1232,  0.1660,
         -0.0684,  0.1110,  0.0259, -0.1410, -0.0232,  0.1353,  0.1360,  0.2298,
         -0.0344,  0.2365, -0.0416, -0.0583, -0.0900, -0.0559]],
       requires_grad=True)
Parameter containing:
tensor(

In [55]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5438596606254578


#### Use built in optimizer

In [56]:
# Definne the model
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network =  nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self, features):
        out = self.network(features)
        return out



In [57]:
criterion = nn.BCELoss()

model = MySimpleNN(X_train_tensor.shape[1])

optimizer=torch.optim.SGD(model.parameters(), lr= learning_rate)

for epoch in range(epochs):

    #Forward
    y_pred = model(X_train_tensor)

    #Loss
    loss = criterion(y_pred, y_train_tensor.view(-1,1))

    #backkward
    loss.backward()

    #paramter update
    optimizer.step()

    #zero grad
    optimizer.zero_grad()
    print(f"Epoch: {epoch+1} , loss: {loss.item()}")

Epoch: 1 , loss: 0.6758602857589722
Epoch: 2 , loss: 0.6567738056182861
Epoch: 3 , loss: 0.6385887265205383
Epoch: 4 , loss: 0.6206203103065491
Epoch: 5 , loss: 0.6034156680107117
Epoch: 6 , loss: 0.5865950584411621
Epoch: 7 , loss: 0.5700075030326843
Epoch: 8 , loss: 0.5537471175193787
Epoch: 9 , loss: 0.5376129746437073
Epoch: 10 , loss: 0.5212992429733276
Epoch: 11 , loss: 0.505332887172699
Epoch: 12 , loss: 0.48961421847343445
Epoch: 13 , loss: 0.47393715381622314
Epoch: 14 , loss: 0.4583646357059479
Epoch: 15 , loss: 0.44319745898246765
Epoch: 16 , loss: 0.4284417927265167
Epoch: 17 , loss: 0.41403087973594666
Epoch: 18 , loss: 0.4000888764858246
Epoch: 19 , loss: 0.38660529255867004
Epoch: 20 , loss: 0.37362247705459595
Epoch: 21 , loss: 0.3612004518508911
Epoch: 22 , loss: 0.3491678535938263
Epoch: 23 , loss: 0.33762720227241516
Epoch: 24 , loss: 0.3266150951385498
Epoch: 25 , loss: 0.31602951884269714


## Using mini batch SGD, untill now GD was going that is full dataset was given as input 

##### Here we have the X_train_tensor and y_train_tensor ready in tabular , and sometime these are not availale as easy as it is there , and also if we want to apply something on all data than we don't have anything and also if we want to shuffle and do paraller processing , so for all of these we have Dataset and Dataloader

In [58]:
batch_size =32
epochs=25
learning_rate= 0.1
criterion = nn.BCELoss()
n_samples = len(X_train_tensor)
model = MySimpleNN(X_train_tensor.shape[1])

optimizer=torch.optim.SGD(model.parameters(), lr= learning_rate)

for epoch in range(epochs):
    
    for start_idx in range(0, n_samples, batch_size):
        end_idx = start_idx+ batch_size
        X_batch = X_train_tensor[start_idx:end_idx]
        y_batch = y_train_tensor[start_idx:end_idx]

        #Forward
        y_pred = model(X_batch)

        #Loss
        loss = criterion(y_pred, y_batch.view(-1,1))

        #backkward
        loss.backward()

        #paramter update
        optimizer.step()

        #zero grad
        optimizer.zero_grad()
    print(f"Epoch: {epoch+1} , loss: {loss.item()}")

Epoch: 1 , loss: 0.5795527696609497
Epoch: 2 , loss: 0.37572285532951355
Epoch: 3 , loss: 0.2591848075389862
Epoch: 4 , loss: 0.17249147593975067
Epoch: 5 , loss: 0.11731104552745819
Epoch: 6 , loss: 0.08386725932359695
Epoch: 7 , loss: 0.06280896067619324
Epoch: 8 , loss: 0.04918437823653221
Epoch: 9 , loss: 0.03985678032040596
Epoch: 10 , loss: 0.033180736005306244
Epoch: 11 , loss: 0.028220126405358315
Epoch: 12 , loss: 0.02445669285953045
Epoch: 13 , loss: 0.021395178511738777
Epoch: 14 , loss: 0.018822507932782173
Epoch: 15 , loss: 0.016777072101831436
Epoch: 16 , loss: 0.01504064816981554
Epoch: 17 , loss: 0.01361093856394291
Epoch: 18 , loss: 0.012517332099378109
Epoch: 19 , loss: 0.011434225365519524
Epoch: 20 , loss: 0.010635294951498508
Epoch: 21 , loss: 0.009908589534461498
Epoch: 22 , loss: 0.009114272892475128
Epoch: 23 , loss: 0.00847525242716074
Epoch: 24 , loss: 0.007937160320580006
Epoch: 25 , loss: 0.0074122450314462185


### Batch processing using Dataset and DataLoader

In [59]:
from sklearn.datasets import make_classification
import torch

In [60]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [61]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [62]:
X.shape, y

((10, 2), array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [63]:
X = torch.tensor(X, dtype = torch.float32)
y= torch.tensor(y, dtype=torch.long)

In [66]:
from torch.utils.data import Dataset, DataLoader

In [67]:
### using Dataset, this  is used to perform any type of preprocessing in overall dataset
class Custom_Dataset(Dataset):
    def __init__(self, features, labels):
        self.features=features
        self.labels= labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        
        return self.features[index], self.labels[index]

In [68]:
dataset= Custom_Dataset(X,y)

In [72]:
len(dataset), dataset.features, dataset.labels

(10,
 tensor([[ 1.0683, -0.9701],
         [-1.1402, -0.8388],
         [-2.8954,  1.9769],
         [-0.7206, -0.9606],
         [-1.9629, -0.9923],
         [-0.9382, -0.5430],
         [ 1.7273, -1.1858],
         [ 1.7774,  1.5116],
         [ 1.8997,  0.8344],
         [-0.5872, -1.9717]]),
 tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

In [73]:
dataloader = DataLoader(dataset, batch_size=2, shuffle = True) # So for 10 points if batch size is  2 , than there are 5 batches
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[ 1.8997,  0.8344],
        [-2.8954,  1.9769]])
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.7774,  1.5116]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [-0.5872, -1.9717]])
tensor([0, 0])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [-0.7206, -0.9606]])
tensor([1, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.0683, -0.9701]])
tensor([1, 1])
--------------------------------------------------


### Applying Dataset and DataLoader for processing in batches

In [74]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv') 
df.head()
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.head()
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train
y_train
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test) 
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()
X_train_tensor.shape
y_train_tensor.shape


torch.Size([455])

In [75]:
# Dataset
class Custom_Dataset(Dataset):
    def __init__(self, features, labels):
        self.features=features
        self.labels= labels
    
    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self, index):
        
        return self.features[index], self.labels[index]

In [76]:
train_dataset= Custom_Dataset(X_train_tensor, y_train_tensor)
test_dataset= Custom_Dataset(X_test_tensor, y_test_tensor)
train_dataset[10]

(tensor([ 1.7508,  0.5342,  1.6759,  1.7584, -0.3696,  0.1333,  0.1020,  0.7132,
         -0.7204, -1.0432,  0.5772, -0.5307,  0.6085,  0.6421, -0.2423, -0.3545,
         -0.2834,  0.4857, -0.7181, -0.7398,  1.6238,  0.0899,  1.5594,  1.5231,
          0.0049, -0.1201, -0.0125,  0.9277, -0.4852, -0.9257]),
 tensor(1.))

In [77]:
train_loader =DataLoader(train_dataset, batch_size=32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

In [78]:
# Definne the model
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network =  nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self, features):
        out = self.network(features)
        return out

In [79]:
learning_rate= 0.1
epochs=25
model =MySimpleNN(X_train_tensor.shape[1])
optimizer= torch.optim.SGD(model.parameters(), lr = learning_rate)
criterion= nn.BCELoss() 
# define loop
for epoch in range(epochs):
    for batch_features, batch_labels in train_loader:

        #Forward
        y_pred = model(batch_features)

        #Loss
        loss= criterion(y_pred, batch_labels.view(-1,1))

        #backward pass
        loss.backward()

        # parameters update
        optimizer.step()
    print(f"Epoch: {epoch+1} , loss: {loss.item()}")

Epoch: 1 , loss: 0.2043236643075943
Epoch: 2 , loss: 2.3375144004821777
Epoch: 3 , loss: 0.0022446538787335157
Epoch: 4 , loss: 3.624991403130066e-20
Epoch: 5 , loss: 5.365813349200721e-10
Epoch: 6 , loss: 9.811769996304065e-05
Epoch: 7 , loss: 0.9066342115402222
Epoch: 8 , loss: 1.720682405448315e-07
Epoch: 9 , loss: 1.2982219457626343
Epoch: 10 , loss: 1.606576370249968e-05
Epoch: 11 , loss: 1.8063074350357056
Epoch: 12 , loss: 3.8208509067771956e-05
Epoch: 13 , loss: 14.285761833190918
Epoch: 14 , loss: 3.9944723539520055e-05
Epoch: 15 , loss: 8.191468805307522e-05
Epoch: 16 , loss: 0.0004264604358468205
Epoch: 17 , loss: 0.0006997570162639022
Epoch: 18 , loss: 0.005690908990800381
Epoch: 19 , loss: 0.01282199565321207
Epoch: 20 , loss: 0.05178327113389969
Epoch: 21 , loss: 0.0
Epoch: 22 , loss: 0.1045197919011116
Epoch: 23 , loss: 0.08015710860490799
Epoch: 24 , loss: 0.01810978725552559
Epoch: 25 , loss: 0.0


### Evaluation

In [80]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9410
