In [92]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [93]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [94]:
df.shape

(569, 33)

In [95]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [96]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [97]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [98]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [99]:
X_train


array([[-0.93091502, -0.84932074, -0.89508238, ..., -0.52768387,
        -0.52837634,  1.32589719],
       [ 1.47023828,  0.77335848,  1.49593289, ...,  0.85716877,
         0.45486127,  0.44890853],
       [-1.31076012, -0.78082337, -1.32227375, ..., -0.64073306,
        -0.2456152 , -0.13038164],
       ...,
       [ 0.8540387 , -0.03207619,  0.90540364, ...,  2.12593325,
         0.31990709,  0.36004331],
       [-0.01674099, -0.76428952, -0.08383757, ..., -0.60563311,
        -0.29702632, -0.65468645],
       [-0.77758837, -1.98307042, -0.77236956, ..., -0.37695161,
         0.17049353,  0.061234  ]])

In [100]:
y_train

474    B
198    M
234    B
132    M
145    B
      ..
75     M
513    B
230    M
437    B
120    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [101]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [102]:
y_train

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,

### Numpy arrays to PyTorch tensors

In [103]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()


In [83]:
X_train_tensor.shape

torch.Size([455, 30])

In [84]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [ ]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1, dtype= torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
    def forward(self, X):
        z= torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
    

In [20]:
## Important parameters
learning_rate= 0.1
epochs=25

In [ ]:
#training
model = MySimpleNN(X_train_tensor)
model.weights
for epoch in range(epochs):

     #Forward pass
     y_pred = model.forward(X_train_tensor)
     #print(y_pred)


    #loss calculate
     loss = model.loss_function(y_pred, y_train_tensor)
     
     #backword pass
     loss.backward()


     #parameters update, 
     with torch.no_grad(): # For not tracking gradient here
        model.weights-=learning_rate * model.weights.grad
        model.bias-= learning_rate * model.bias.grad
        
    #zero gradient  # To not accumalate gradient
     model.weights.grad.zero_()
     model.bias.grad.zero_()
    #Print loss
     print(f"Epoch: {epoch+1}, loss: {loss.item()}")
     



Epoch: 1, loss: 3.34648415538911
Epoch: 2, loss: 3.214050667913655
Epoch: 3, loss: 3.073383007131406
Epoch: 4, loss: 2.92396347378261
Epoch: 5, loss: 2.7720878360414267
Epoch: 6, loss: 2.6186021499762164
Epoch: 7, loss: 2.4647861907050914
Epoch: 8, loss: 2.3097050031498334
Epoch: 9, loss: 2.155325872964272
Epoch: 10, loss: 2.0025751951913735
Epoch: 11, loss: 1.8467587975064454
Epoch: 12, loss: 1.6966736605374093
Epoch: 13, loss: 1.5566468339244226
Epoch: 14, loss: 1.4281476118115448
Epoch: 15, loss: 1.3126209113010394
Epoch: 16, loss: 1.2113101671819693
Epoch: 17, loss: 1.1249837523276494
Epoch: 18, loss: 1.0535838532178259
Epoch: 19, loss: 0.996064355123536
Epoch: 20, loss: 0.9506245328307815
Epoch: 21, loss: 0.9151214750580201
Epoch: 22, loss: 0.8873970406301345
Epoch: 23, loss: 0.8654919531902489
Epoch: 24, loss: 0.8477827066768836
Epoch: 25, loss: 0.833033779355246


In [28]:
model.weights

tensor([[-0.0274],
        [ 0.3188],
        [ 0.3545],
        [ 0.4034],
        [-0.1115],
        [-0.2822],
        [ 0.3035],
        [-0.2097],
        [-0.0725],
        [-0.0762],
        [ 0.1226],
        [ 0.5294],
        [-0.0315],
        [-0.3373],
        [ 0.6784],
        [ 0.1233],
        [-0.2799],
        [-0.0253],
        [ 0.0211],
        [ 0.1763],
        [ 0.1371],
        [ 0.1232],
        [-0.0393],
        [-0.0564],
        [ 0.1883],
        [-0.0441],
        [-0.0765],
        [-0.3391],
        [-0.0109],
        [ 0.3011]], dtype=torch.float64, requires_grad=True)

In [22]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [31]:
#Evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5318559408187866


In [15]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


### Important Parameters

In [16]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():  #To not track gradient here
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients , to  not accumate gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.8525842857844483
Epoch: 2, Loss: 3.7396124593481463
Epoch: 3, Loss: 3.6220240878825023
Epoch: 4, Loss: 3.494599926928255
Epoch: 5, Loss: 3.358916544046054
Epoch: 6, Loss: 3.2200883413819823
Epoch: 7, Loss: 3.0789618923994784
Epoch: 8, Loss: 2.9344400420891406
Epoch: 9, Loss: 2.7830547924677314
Epoch: 10, Loss: 2.633595375240307
Epoch: 11, Loss: 2.482931499488942
Epoch: 12, Loss: 2.3304676406379716
Epoch: 13, Loss: 2.176020728698768
Epoch: 14, Loss: 2.024789667542864
Epoch: 15, Loss: 1.8722287799122925
Epoch: 16, Loss: 1.7219232752265807
Epoch: 17, Loss: 1.581191157589141
Epoch: 18, Loss: 1.4497766593737325
Epoch: 19, Loss: 1.328445661782137
Epoch: 20, Loss: 1.2211144664014186
Epoch: 21, Loss: 1.1285445856694158
Epoch: 22, Loss: 1.0507599045455545
Epoch: 23, Loss: 0.9869634082470181
Epoch: 24, Loss: 0.9356672779553706
Epoch: 25, Loss: 0.8949553026951054


In [18]:
model.bias

tensor([-0.1491], dtype=torch.float64, requires_grad=True)

### Evaluation

In [19]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5678670406341553


🚀 1. Improvements Planned (Notebook Cell with Print Explanation)

In [32]:
print("Training Pipeline Improvements Implemented:")
print("1️⃣ Model defined using nn.Linear instead of manual weights/bias.")
print("2️⃣ Activation functions from nn (Sigmoid, ReLU).")
print("3️⃣ Built-in loss function (nn.BCELoss).")
print("4️⃣ Parameter updates using torch.optim.SGD.")

Training Pipeline Improvements Implemented:
1️⃣ Model defined using nn.Linear instead of manual weights/bias.
2️⃣ Activation functions from nn (Sigmoid, ReLU).
3️⃣ Built-in loss function (nn.BCELoss).
4️⃣ Parameter updates using torch.optim.SGD.


### Simple  one  node network

In [ ]:
#practice one neural  layer
# 5 features and 1 output , binary classification
import torch 
import torch.nn as nn
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid= nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out= self.sigmoid(out)
        return out 

In [50]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.4590],
        [0.5535],
        [0.4887],
        [0.4988],
        [0.5381],
        [0.5092],
        [0.4910],
        [0.4803],
        [0.5149],
        [0.5068]], grad_fn=<SigmoidBackward0>)

In [54]:
model.linear

Linear(in_features=5, out_features=1, bias=True)

In [55]:
model.linear.weight

Parameter containing:
tensor([[-0.4384, -0.1313,  0.0846,  0.0129,  0.3492]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([0.1003], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model, input_size= (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Simple 3 node in 1st layer and one  node  in second  layer network

In [ ]:
#Practice with 3 neuron in first layer and one neuron in second layer
import torch
import torch.nn as nn
class Model(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features, 3) #Linear 1 is the name of the  first layer, with 5 input and 3 ouput
        self.relu = nn.ReLU()    #Applying ReLU on it 
        self.linear2 = nn.Linear(3,1)  # Linear 2 is the name of the second layer with 3 input and one output 
        self.sigmoid = nn.Sigmoid()    #Applying Sigmoid on it
    
    def forward(self, features):

        out = self.linear1(features)
        out = self.relu(out)
        out= self.linear2(out)
        out = self.sigmoid(out)
        
        return out


In [62]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5708],
        [0.5642],
        [0.5801],
        [0.5801],
        [0.5801],
        [0.5801],
        [0.5709],
        [0.5801],
        [0.5801],
        [0.5801]], grad_fn=<SigmoidBackward0>)

In [64]:
model.linear1.weight

Parameter containing:
tensor([[-0.4014, -0.1231, -0.0488,  0.3111, -0.1785],
        [ 0.2549, -0.3018,  0.1055, -0.4180,  0.1317],
        [-0.0682, -0.3761,  0.3112, -0.4085, -0.0664]], requires_grad=True)

In [65]:
model.linear1.bias

Parameter containing:
tensor([-0.0374,  0.0680,  0.2832], requires_grad=True)

In [66]:
from torchinfo import summary
summary(model, input_size= (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Same network Sequential container 

In [67]:
import torch 
import torch.nn as nn
class Model(nn.Module):

    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out 

In [68]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.3400],
        [0.3750],
        [0.3517],
        [0.3560],
        [0.3671],
        [0.3488],
        [0.3674],
        [0.3708],
        [0.3708],
        [0.3440]], grad_fn=<SigmoidBackward0>)

##### How to find the weights of the layer like we did before ?

In [70]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [85]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [104]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.network(features)
        return out 
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Binary cross entropy manually
        loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
        return loss

In [90]:
learning_rate= 0.1
epochs= 25

In [106]:
model = MySimpleNN(X_train_tensor.shape[1])

for epoch in range(epochs):
    # Forward
    y_pred = model(X_train_tensor)
    #Losss
    loss= model.loss_function(y_pred, y_train_tensor)
    #Calculate gradient/ Backward pass
    loss.backward()
    #Update weight
    with torch.no_grad(): #So that it does not track gradient while updating weight
        for param in model.parameters():        # FIXED
            param -= learning_rate * param.grad

    #Gradient not to accumalate
     # Reset gradients
    model.zero_grad()  
    print(f"Epoch : {epoch+1}, loss: {loss.item()}")


Epoch : 1, loss: 0.8378174901008606
Epoch : 2, loss: 0.8246443867683411
Epoch : 3, loss: 0.8127707242965698
Epoch : 4, loss: 0.8020095825195312
Epoch : 5, loss: 0.792217493057251
Epoch : 6, loss: 0.7832663059234619
Epoch : 7, loss: 0.775044322013855
Epoch : 8, loss: 0.7674670219421387
Epoch : 9, loss: 0.7604628801345825
Epoch : 10, loss: 0.753974437713623
Epoch : 11, loss: 0.7479523420333862
Epoch : 12, loss: 0.7423533797264099
Epoch : 13, loss: 0.7371394634246826
Epoch : 14, loss: 0.732278048992157
Epoch : 15, loss: 0.7277412414550781
Epoch : 16, loss: 0.723501980304718
Epoch : 17, loss: 0.7195380330085754
Epoch : 18, loss: 0.7158287167549133
Epoch : 19, loss: 0.7123559713363647
Epoch : 20, loss: 0.7091031670570374
Epoch : 21, loss: 0.7060551047325134
Epoch : 22, loss: 0.7031984329223633
Epoch : 23, loss: 0.7005199193954468
Epoch : 24, loss: 0.6980080008506775
Epoch : 25, loss: 0.6956517696380615


### Using built in loss function 

In [109]:
class MySimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self, features):

        out = self.network(features)
        return out 
    
criterion = nn.BCELoss()

    

In [ ]:
model = MySimpleNN(X_train_tensor.shape[1])
for epoch in range(epochs):
    # Forward
    y_pred= model(X_train_tensor)
    #Loss
    loss = criterion(y_pred, y_train_tensor.view(-1,1))

    #Backward pass
    loss.backward()

    #parameterss update
    with torch.no_grad():
        for param in model.parameters():
            param-=learning_rate*param.grad
   #Gradient not to accumalate
   # Reset gradients
    model.zero_grad()  
    print(f"Epoch : {epoch+1}, loss: {loss.item()}")
    

Epoch : 1, loss: 0.5971823930740356
Epoch : 2, loss: 0.5881367325782776
Epoch : 3, loss: 0.5782986879348755
Epoch : 4, loss: 0.5675761103630066
Epoch : 5, loss: 0.5558875203132629
Epoch : 6, loss: 0.5433948040008545
Epoch : 7, loss: 0.5301297903060913
Epoch : 8, loss: 0.5161307454109192
Epoch : 9, loss: 0.501541018486023
Epoch : 10, loss: 0.4863570034503937
Epoch : 11, loss: 0.4707859456539154
Epoch : 12, loss: 0.4550582468509674
Epoch : 13, loss: 0.4392997920513153
Epoch : 14, loss: 0.42359960079193115
Epoch : 15, loss: 0.40809714794158936
Epoch : 16, loss: 0.39296066761016846
Epoch : 17, loss: 0.3782966434955597
Epoch : 18, loss: 0.3641595244407654
Epoch : 19, loss: 0.35061317682266235
Epoch : 20, loss: 0.3376784920692444
Epoch : 21, loss: 0.32536107301712036
Epoch : 22, loss: 0.3136766254901886
Epoch : 23, loss: 0.3026413917541504
Epoch : 24, loss: 0.2921672463417053
Epoch : 25, loss: 0.28225505352020264


In [113]:
model.parameters

<bound method Module.parameters of MySimpleNN(
  (network): Sequential(
    (0): Linear(in_features=30, out_features=3, bias=True)
    (1): ReLU()
    (2): Linear(in_features=3, out_features=1, bias=True)
    (3): Sigmoid()
  )
)>

In [116]:
#1. View first layer weights and bias
print(model.network[0].weight)
print(model.network[0].bias)

Parameter containing:
tensor([[ 2.0217e-01, -3.2830e-03,  1.0309e-02,  1.9260e-01,  5.2893e-02,
         -5.9100e-02,  1.1357e-02, -1.0401e-01, -7.8445e-02,  1.4192e-01,
         -1.8828e-02, -8.1371e-02,  3.9067e-03, -1.2222e-01,  2.4417e-02,
          1.7195e-02,  1.5300e-01,  1.6301e-01,  9.8964e-02, -5.7251e-02,
          3.2698e-03, -7.5073e-02, -2.0048e-02, -1.1760e-01, -1.2308e-01,
          5.2164e-02, -3.5888e-02,  1.0415e-01,  5.9324e-02,  1.4946e-01],
        [-1.7890e-01, -6.2967e-02, -6.0629e-02, -2.7377e-01, -5.9381e-02,
         -9.2865e-02, -2.3727e-01, -1.6365e-01,  2.8963e-02,  8.7161e-02,
         -2.4460e-01, -4.3300e-02, -2.0502e-01, -1.7194e-01, -1.3082e-01,
         -4.3104e-02,  5.5739e-02,  1.6038e-02,  2.9654e-02,  1.6848e-01,
         -2.8561e-01, -1.2164e-01,  4.9573e-02, -1.5089e-01, -1.3744e-01,
         -9.4351e-02, -1.0347e-01, -1.2136e-01, -8.2830e-03, -1.7793e-01],
        [-3.8134e-02,  2.5672e-02,  1.8469e-01,  2.3896e-01,  1.7032e-01,
          2.29

In [117]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.542474627494812


#### Use build in optimizer

In [119]:
# Definne the model
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network =  nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self, features):
        out = self.network(features)
        return out



In [120]:
criterion = nn.BCELoss()

model = MySimpleNN(X_train_tensor.shape[1])

optimizer=torch.optim.SGD(model.parameters(), lr= learning_rate)

for epoch in range(epochs):

    #Forward
    y_pred = model(X_train_tensor)

    #Loss
    loss = criterion(y_pred, y_train_tensor.view(-1,1))

    #backkward
    loss.backward()

    #paramter update
    optimizer.step()

    #zero grad
    optimizer.zero_grad()
    print(f"Epoch: {epoch+1} , loss: {loss.item()}")

Epoch: 1 , loss: 0.6945545077323914
Epoch: 2 , loss: 0.6835947632789612
Epoch: 3 , loss: 0.6717745661735535
Epoch: 4 , loss: 0.6591335535049438
Epoch: 5 , loss: 0.6452563405036926
Epoch: 6 , loss: 0.6298803687095642
Epoch: 7 , loss: 0.6135919094085693
Epoch: 8 , loss: 0.5959268808364868
Epoch: 9 , loss: 0.5779425501823425
Epoch: 10 , loss: 0.5602956414222717
Epoch: 11 , loss: 0.5433548092842102
Epoch: 12 , loss: 0.527420699596405
Epoch: 13 , loss: 0.512360155582428
Epoch: 14 , loss: 0.49834245443344116
Epoch: 15 , loss: 0.4852290451526642
Epoch: 16 , loss: 0.47286471724510193
Epoch: 17 , loss: 0.46129927039146423
Epoch: 18 , loss: 0.45053523778915405
Epoch: 19 , loss: 0.44046953320503235
Epoch: 20 , loss: 0.4310433864593506
Epoch: 21 , loss: 0.42221659421920776
Epoch: 22 , loss: 0.4139299988746643
Epoch: 23 , loss: 0.4060523211956024
Epoch: 24 , loss: 0.39858928322792053
Epoch: 25 , loss: 0.39145782589912415
